"""House Model

Revision ID: 8e6e24625250
Revises: 7c2c8e94c8cb
Create Date: 2023-06-08 23:32:17.633787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6e24625250'
down_revision = '7c2c8e94c8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
